backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: "plantes-interieur"
    label: "Plantes d'intérieur"
    folder: "src/pages/plantes-interieur"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "plantes-interieur"}
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Date de publication", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Mettre en avant", name: "featuredpost", widget: "boolean"}
      - {label: "Image de couverture", name: "featuredimage", widget: image}
      - {label: "Corps", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}

  - name: "fruits-legumes"
    label: "Fruits & Légumes"
    folder: "src/pages/fruits-legumes"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "fruits-legumes"}
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Date de publication", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Mettre en avant", name: "featuredpost", widget: "boolean"}
      - {label: "Image de couverture", name: "featuredimage", widget: image}
      - {label: "Corps", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}    

  - name: "plantes-potageres"
    label: "Plantes potagères"
    folder: "src/pages/plantes-potageres"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "plantes-potageres"}
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Date de publication", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Mettre en avant", name: "featuredpost", widget: "boolean"}
      - {label: "Image de couverture", name: "featuredimage", widget: image}
      - {label: "Corps", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Page d'accueil"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Titre, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: En-tête, name: heading, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Contenu, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
      - file: "src/pages/about/index.md"
        label: "A propos"
        name: "a-propos"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Titre", name: "title", widget: "string"}
          - {label: "Corps", name: "body", widget: "markdown"}
      